import React from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Button } from '../components';
import { Specimen } from './shared';
const meta = { title: 'Components/Button', component: Button, tags: ['autodocs'], parameters: { docs: { description: { component: "Use one primary action per decision. Reserve destructive styling for actions that can replace user data. Loading keeps a stable label and blocks duplicate submissions.\n\n### Accessibility\nNative button: Tab to focus, Space or Enter to activate. Loading sets aria-busy and disables activation. Focus uses a three-pixel semantic ring.\n\n### Implementation status\nButton primitives are proposed extractions of inline app controls. Hover, pressed and focus stories pin visual states for inspection; test actual pointer and keyboard behavior in Default.\n\n### Design reference\n[Figma system](https://www.figma.com/design/F4cJIG7cCiURqp30nqszk9). Use the toolbar to review Light/Dark and Standard/Reduced motion. Automated checks are supplemented by documented manual checks." } } }, args: {"intent": "primary", "state": "default"} } satisfies Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof meta>;
export const PrimaryDefault: Story = { args: {"intent": "primary", "state": "default"} };
export const PrimaryHover: Story = { args: {"intent": "primary", "state": "hover"} };
export const PrimaryPressed: Story = { args: {"intent": "primary", "state": "pressed"} };
export const PrimaryFocus: Story = { args: {"intent": "primary", "state": "focus"} };
export const PrimaryDisabled: Story = { args: {"intent": "primary", "state": "disabled"} };
export const PrimaryLoading: Story = { args: {"intent": "primary", "state": "loading"} };
export const SecondaryDefault: Story = { args: {"intent": "secondary", "state": "default"} };
export const SecondaryHover: Story = { args: {"intent": "secondary", "state": "hover"} };
export const SecondaryPressed: Story = { args: {"intent": "secondary", "state": "pressed"} };
export const SecondaryFocus: Story = { args: {"intent": "secondary", "state": "focus"} };
export const SecondaryDisabled: Story = { args: {"intent": "secondary", "state": "disabled"} };
export const SecondaryLoading: Story = { args: {"intent": "secondary", "state": "loading"} };
export const DestructiveDefault: Story = { args: {"intent": "destructive", "state": "default"} };
export const DestructiveHover: Story = { args: {"intent": "destructive", "state": "hover"} };
export const DestructivePressed: Story = { args: {"intent": "destructive", "state": "pressed"} };
export const DestructiveFocus: Story = { args: {"intent": "destructive", "state": "focus"} };
export const DestructiveDisabled: Story = { args: {"intent": "destructive", "state": "disabled"} };
export const DestructiveLoading: Story = { args: {"intent": "destructive", "state": "loading"} };
export const StateMatrix: Story = { render: () => <div className="tidy-grid"><Specimen key="0" label="primary / default"><Button {...{"intent": "primary", "state": "default"}} /></Specimen><Specimen key="1" label="primary / hover"><Button {...{"intent": "primary", "state": "hover"}} /></Specimen><Specimen key="2" label="primary / pressed"><Button {...{"intent": "primary", "state": "pressed"}} /></Specimen><Specimen key="3" label="primary / focus"><Button {...{"intent": "primary", "state": "focus"}} /></Specimen><Specimen key="4" label="primary / disabled"><Button {...{"intent": "primary", "state": "disabled"}} /></Specimen><Specimen key="5" label="primary / loading"><Button {...{"intent": "primary", "state": "loading"}} /></Specimen><Specimen key="6" label="secondary / default"><Button {...{"intent": "secondary", "state": "default"}} /></Specimen><Specimen key="7" label="secondary / hover"><Button {...{"intent": "secondary", "state": "hover"}} /></Specimen><Specimen key="8" label="secondary / pressed"><Button {...{"intent": "secondary", "state": "pressed"}} /></Specimen><Specimen key="9" label="secondary / focus"><Button {...{"intent": "secondary", "state": "focus"}} /></Specimen><Specimen key="10" label="secondary / disabled"><Button {...{"intent": "secondary", "state": "disabled"}} /></Specimen><Specimen key="11" label="secondary / loading"><Button {...{"intent": "secondary", "state": "loading"}} /></Specimen><Specimen key="12" label="destructive / default"><Button {...{"intent": "destructive", "state": "default"}} /></Specimen><Specimen key="13" label="destructive / hover"><Button {...{"intent": "destructive", "state": "hover"}} /></Specimen><Specimen key="14" label="destructive / pressed"><Button {...{"intent": "destructive", "state": "pressed"}} /></Specimen><Specimen key="15" label="destructive / focus"><Button {...{"intent": "destructive", "state": "focus"}} /></Specimen><Specimen key="16" label="destructive / disabled"><Button {...{"intent": "destructive", "state": "disabled"}} /></Specimen><Specimen key="17" label="destructive / loading"><Button {...{"intent": "destructive", "state": "loading"}} /></Specimen></div> };
