import React from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { IconButton } from '../components';
import { Specimen } from './shared';
const meta = { title: 'Components/IconButton', component: IconButton, tags: ['autodocs'], parameters: { docs: { description: { component: "Use for familiar secondary actions with a concise accessible name. Expanded density offers a larger target; selected communicates a persistent mode.\n\n### Accessibility\nEvery icon-only button has an accessible name. aria-pressed exposes selected state. Tab and Space/Enter use native button behavior.\n\n### Implementation status\nProposed extraction from TopBar and card actions. Do not use an unfamiliar icon without a visible text alternative.\n\n### Design reference\n[Figma system](https://www.figma.com/design/F4cJIG7cCiURqp30nqszk9). Use the toolbar to review Light/Dark and Standard/Reduced motion. Automated checks are supplemented by documented manual checks." } } }, args: {"density": "compact", "state": "default"} } satisfies Meta<typeof IconButton>;
export default meta;
type Story = StoryObj<typeof meta>;
export const CompactDefault: Story = { args: {"density": "compact", "state": "default"} };
export const CompactHover: Story = { args: {"density": "compact", "state": "hover"} };
export const CompactPressed: Story = { args: {"density": "compact", "state": "pressed"} };
export const CompactFocus: Story = { args: {"density": "compact", "state": "focus"} };
export const CompactDisabled: Story = { args: {"density": "compact", "state": "disabled"} };
export const CompactSelected: Story = { args: {"density": "compact", "state": "selected"} };
export const ExpandedDefault: Story = { args: {"density": "expanded", "state": "default"} };
export const ExpandedHover: Story = { args: {"density": "expanded", "state": "hover"} };
export const ExpandedPressed: Story = { args: {"density": "expanded", "state": "pressed"} };
export const ExpandedFocus: Story = { args: {"density": "expanded", "state": "focus"} };
export const ExpandedDisabled: Story = { args: {"density": "expanded", "state": "disabled"} };
export const ExpandedSelected: Story = { args: {"density": "expanded", "state": "selected"} };
export const StateMatrix: Story = { render: () => <div className="tidy-grid"><Specimen key="0" label="compact / default"><IconButton {...{"density": "compact", "state": "default"}} /></Specimen><Specimen key="1" label="compact / hover"><IconButton {...{"density": "compact", "state": "hover"}} /></Specimen><Specimen key="2" label="compact / pressed"><IconButton {...{"density": "compact", "state": "pressed"}} /></Specimen><Specimen key="3" label="compact / focus"><IconButton {...{"density": "compact", "state": "focus"}} /></Specimen><Specimen key="4" label="compact / disabled"><IconButton {...{"density": "compact", "state": "disabled"}} /></Specimen><Specimen key="5" label="compact / selected"><IconButton {...{"density": "compact", "state": "selected"}} /></Specimen><Specimen key="6" label="expanded / default"><IconButton {...{"density": "expanded", "state": "default"}} /></Specimen><Specimen key="7" label="expanded / hover"><IconButton {...{"density": "expanded", "state": "hover"}} /></Specimen><Specimen key="8" label="expanded / pressed"><IconButton {...{"density": "expanded", "state": "pressed"}} /></Specimen><Specimen key="9" label="expanded / focus"><IconButton {...{"density": "expanded", "state": "focus"}} /></Specimen><Specimen key="10" label="expanded / disabled"><IconButton {...{"density": "expanded", "state": "disabled"}} /></Specimen><Specimen key="11" label="expanded / selected"><IconButton {...{"density": "expanded", "state": "selected"}} /></Specimen></div> };
