import React from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { RuleCard } from '../components';
import { Specimen } from './shared';
const meta = { title: 'Components/RuleCard', component: RuleCard, tags: ['autodocs'], parameters: { docs: { description: { component: "Separate enablement from disclosure. Opening a rule reveals configuration without silently enabling it. Four extension chips are illustrative samples.\n\n### Accessibility\nDisclosure exposes aria-expanded. Its toggle has a category-specific name. Extension choices are keyboard-operable buttons.\n\n### Implementation status\nDisabled in the Figma matrix means the category is off; its toggle remains operable. Current app stories show the complete extension inventory.\n\n### Design reference\n[Figma system](https://www.figma.com/design/F4cJIG7cCiURqp30nqszk9). Use the toolbar to review Light/Dark and Standard/Reduced motion. Automated checks are supplemented by documented manual checks." } } }, args: {"category": "Documents", "state": "collapsed"} } satisfies Meta<typeof RuleCard>;
export default meta;
type Story = StoryObj<typeof meta>;
export const DocumentsCollapsed: Story = { args: {"category": "Documents", "state": "collapsed"} };
export const DocumentsExpanded: Story = { args: {"category": "Documents", "state": "expanded"} };
export const DocumentsDisabled: Story = { args: {"category": "Documents", "state": "disabled"} };
export const ImagesCollapsed: Story = { args: {"category": "Images", "state": "collapsed"} };
export const ImagesExpanded: Story = { args: {"category": "Images", "state": "expanded"} };
export const ImagesDisabled: Story = { args: {"category": "Images", "state": "disabled"} };
export const AudioCollapsed: Story = { args: {"category": "Audio", "state": "collapsed"} };
export const AudioExpanded: Story = { args: {"category": "Audio", "state": "expanded"} };
export const AudioDisabled: Story = { args: {"category": "Audio", "state": "disabled"} };
export const VideoCollapsed: Story = { args: {"category": "Video", "state": "collapsed"} };
export const VideoExpanded: Story = { args: {"category": "Video", "state": "expanded"} };
export const VideoDisabled: Story = { args: {"category": "Video", "state": "disabled"} };
export const ArchivesCollapsed: Story = { args: {"category": "Archives", "state": "collapsed"} };
export const ArchivesExpanded: Story = { args: {"category": "Archives", "state": "expanded"} };
export const ArchivesDisabled: Story = { args: {"category": "Archives", "state": "disabled"} };
export const StateMatrix: Story = { render: () => <div className="tidy-grid"><Specimen key="0" label="Documents / collapsed"><RuleCard {...{"category": "Documents", "state": "collapsed"}} /></Specimen><Specimen key="1" label="Documents / expanded"><RuleCard {...{"category": "Documents", "state": "expanded"}} /></Specimen><Specimen key="2" label="Documents / disabled"><RuleCard {...{"category": "Documents", "state": "disabled"}} /></Specimen><Specimen key="3" label="Images / collapsed"><RuleCard {...{"category": "Images", "state": "collapsed"}} /></Specimen><Specimen key="4" label="Images / expanded"><RuleCard {...{"category": "Images", "state": "expanded"}} /></Specimen><Specimen key="5" label="Images / disabled"><RuleCard {...{"category": "Images", "state": "disabled"}} /></Specimen><Specimen key="6" label="Audio / collapsed"><RuleCard {...{"category": "Audio", "state": "collapsed"}} /></Specimen><Specimen key="7" label="Audio / expanded"><RuleCard {...{"category": "Audio", "state": "expanded"}} /></Specimen><Specimen key="8" label="Audio / disabled"><RuleCard {...{"category": "Audio", "state": "disabled"}} /></Specimen><Specimen key="9" label="Video / collapsed"><RuleCard {...{"category": "Video", "state": "collapsed"}} /></Specimen><Specimen key="10" label="Video / expanded"><RuleCard {...{"category": "Video", "state": "expanded"}} /></Specimen><Specimen key="11" label="Video / disabled"><RuleCard {...{"category": "Video", "state": "disabled"}} /></Specimen><Specimen key="12" label="Archives / collapsed"><RuleCard {...{"category": "Archives", "state": "collapsed"}} /></Specimen><Specimen key="13" label="Archives / expanded"><RuleCard {...{"category": "Archives", "state": "expanded"}} /></Specimen><Specimen key="14" label="Archives / disabled"><RuleCard {...{"category": "Archives", "state": "disabled"}} /></Specimen></div> };
