import React from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { OrganizerJourney } from '../components/OrganizerJourney';
import { figma } from './shared';
function OverviewPage() {
  return <main className="tidy-page"><header className="tidy-hero"><p className="tidy-eyebrow">Tidy / Product design system / v1</p><h1>Order you can understand.</h1><p className="tidy-lead">A macOS file organizer, expressed as a system of clear decisions, inspectable actions, and honest feedback.</p><div className="tidy-wrap"><a href={figma} target="_blank" rel="noreferrer">Open the Figma system ↗</a><span aria-hidden="true"> / </span><a target="_top" href="./?path=/story/workflows-manual-organization--configure">Explore the interactive journey →</a></div></header><section className="tidy-grid">{[['108','Figma variables, exported to typed tokens and CSS.'],['15','Component families with 120 named variant stories.'],['2','Appearance modes, with a reduced-motion option.']].map(([value, label]) => <div className="tidy-card tidy-stack" key={value}><h2>{value}</h2><p className="tidy-muted">{label}</p></div>)}</section><section className="tidy-stack"><p className="tidy-eyebrow">The system in context</p><h2>Control before automation.</h2><p className="tidy-lead">Review the rules. Inspect the destination. Understand what changed. The same principles connect the smallest control to the complete workflow.</p><OrganizerJourney /></section><section className="tidy-grid"><article className="tidy-card tidy-stack"><h3>For a design review</h3><p>Start with the foundations, compare component states, then follow the manual organization journey. Each family documents purpose, behavior, accessibility, and implementation status.</p><a target="_top" href="./?path=/story/practice--interview-walkthrough">Interview walkthrough →</a></article><article className="tidy-card tidy-stack"><h3>For implementation</h3><p>Components contains the proposed Figma-aligned library. In the app renders existing production-source React components for comparison. This distinction makes adoption work visible.</p><a target="_top" href="./?path=/story/practice--source-mapping">Source and adoption map →</a></article></section><aside className="tidy-callout"><strong>Authorship and evidence</strong><p>Eric Auzenne designed and built Tidy. This companion system documents the app and proposed refinements. Demonstration counts are illustrative. No user-research results, adoption figures, or business outcomes have been invented.</p></aside></main>;
}
export default { title: 'Start here', component: OverviewPage, parameters: { layout: 'fullscreen' } } satisfies Meta<typeof OverviewPage>;
export const Overview: StoryObj<typeof OverviewPage> = {};
