import React, { useState } from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { expect, userEvent, within } from 'storybook/test';
import { Button, FolderCard, RuleCard, AiCommand, PreviewRow, Feedback, RunStatus, Schedule } from '../components';
import { Page } from './shared';
import { OrganizerJourney } from '../components/OrganizerJourney';
const meta = { title: 'Workflows/Manual organization', component: OrganizerJourney, parameters: { layout: 'fullscreen', docs: { description: { component: 'Proposed system composition. The journey demonstrates manual review, execution feedback and recovery. It has no Electron bridge, filesystem access or AI API calls. Scheduled runs follow a different contract and bypass manual preview.' } } }, decorators: [(Story) => <Page eyebrow="Applied system" title="From intent to evidence" intro="A complete manual run, with the decisions visible at each step. All file names and counts are demonstration data."><Story /></Page>] } satisfies Meta<typeof OrganizerJourney>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Configure: Story = {};
export const Preview: Story = { args: { initial: 'preview' } };
export const Running: Story = { args: { initial: 'running' } };
export const Complete: Story = { args: { initial: 'complete' } };
export const PartialFailure: Story = { args: { initial: 'error' } };
export const Undo: Story = { args: { initial: 'undone' } };
export const Dark: Story = { globals: { theme: 'dark' } };
export const KeyboardJourney: Story = { play: async ({ canvasElement }) => {
  const canvas = within(canvasElement);
  await userEvent.click(canvas.getByRole('button', { name: 'Run Tidy' }));
  await expect(canvas.getByText('Review before you organize')).toBeVisible();
  await userEvent.click(canvas.getByRole('button', { name: 'Start organizing' }));
  await expect(canvas.getByRole('progressbar')).toHaveAttribute('value', '64');
  await userEvent.click(canvas.getByRole('button', { name: 'Show successful result' }));
  await expect(canvas.getByText('Your files are organized')).toBeVisible();
  const undo = canvas.getByRole('button', { name: 'Undo last run' });
  undo.focus(); await userEvent.keyboard('{Enter}');
  await expect(canvas.getByText('Recorded moves reversed')).toBeVisible();
} };
export const FirstUse: Story = { render: () => <div className="tidy-stack"><div className="tidy-grid"><FolderCard state="empty" /><FolderCard role="destination" state="empty" /></div><Feedback tone="information" title="Choose both locations">Select a source and destination before running Tidy.</Feedback><Button state="disabled">Run Tidy</Button></div> };
export const ScheduledRun: Story = { render: () => <Schedule frequency="weekly" /> };
